DROP DATABASE IF EXISTS Person;

CREATE DATABASE Person;

USE Person;

CREATE TABLE Person (
  id INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  subStart VARCHAR(50) NOT NULL,
  subEnd VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);